artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_file: https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv
  raw_data_file_path: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  status_file_name: status.txt
  source_file: artifacts/data_ingestion/data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  source_file: artifacts/data_ingestion/data.csv
  test_file_name: artifacts/data_transformation/preprocessed_data/test.csv
  train_file_name: artifacts/data_transformation/preprocessed_data/train.csv
  preprocessor_file_path: artifacts/data_transformation/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  source_train_file: artifacts/data_transformation/preprocessed_data/train.csv
  source_test_file: artifacts/data_transformation/preprocessed_data/test.csv
  model_file_path: artifacts/model_trainer/model.pkl