name: CI/CD for dockerized IRIS Classification

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs: 
    create_docker:
        needs: build
        runs-on: ubuntu-latest
        steps: 
            - name: build_docker_image
              uses: actions/checkout@v4
              run: docker build . --file Dockerfile --tag workflow-test:$(date +%s)

    build:
        runs-on: ubuntu-latest

        steps:  
        - name: checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install Dependencies
          run: |
            pip install -r requirements.txt
    publish:
        needs: build
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
 
        - name: Login to GitHub
          uses: docker/login-action@v2
          with: 
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v4
          with:
            file: ./Dockerfile 
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/iris-classification:latest

        - name: image_digest
          run: echo ${{ steps.build-and-publish.outputs.digest }}


